server:
  port: 9099

spring:
  application:
    name: my-demo

  datasource:
    dynamic:
      primary: test
      strict: true
      datasource:
        ak_monitor:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password:



#  cloud:
#    nacos:
#      username: ${AK_NACOS_USERNAME:nacos}
#      password: ${AK_NACOS_PASSWORD:nacos}
#      discovery:
#        register-disabled: false
#        server-addr: ${AK_NACOS_SERVER_ADDR:127.0.0.1:8848}
#        #server-addr: ${AK_NACOS_SERVER_ADDR:localhost:8848}
#        namespace: ${AK_NACOS_DISCOVERY_NAMESPACE:test}
#        heart-beat-interval: 3000
#        heart-beat-timeout: 6000
#        ip-delete-timeout: 9000
#        metadata:
#          version: ${AK_APP_VERSION:1.0}
#      config:
#        server-addr: ${AK_NACOS_SERVER_ADDR:127.0.0.1:8848}
#        #server-addr: ${AK_NACOS_SERVER_ADDR:localhost:8848}
#        namespace: ${AK_NACOS_CONFIG_NAMESPACE:test}
#        group: ${AK_NACOS_CONFIG_GROUP:BASE}
#        file-extension: yml
#        extension-configs:
#          - data-id: ak-sentinel-common.yml
#            group: ${AK_NACOS_CONFIG_GROUP:BASE}
#            refresh: true



